### DISCUSSION TITLE
Doesn't seem to have the forecast for next X hours

### DISCUSSION THREAD

**Discussion by simar7** [BJReplay/ha-solcast-solar#159] [Q&A] [answered]
hi everyone! I'm just trying to understand why my setup doesn't show me future data (forecast for next X hours). I've tried to use the time picker to give me the range in the future but my data always ends at the current timestamp. See below:

<img width="2263" alt="image" src="https://github.com/user-attachments/assets/8314de88-5cee-4927-ad1d-d0eacc899dc0">

**Comment by autoSteve** [comment, marked as answer]
That sensor gets calculated from 'now', totalling the expected production over the next X hours. It gets re-calculated every five minutes, and uses interpolated data for inter-30-minute periods.

Because 'now' hasn't happened into the future there is no future data available, so your chart makes sense.

What's the use case that you're trying to solve?

**Reply by simar7** [reply]
I  want to replicate this solcast graph locally 
<img width="1021" alt="IMG_7487" src="https://github.com/user-attachments/assets/f65c04f9-f746-434f-9809-64984a14b821">

**Reply by autoSteve** [reply]
Then the 30-minute detailedForecast attributes are going to be your friend.

There are today, tomorrow, day3, day4, D5, D6, D7 sensors that can be used to pull the details from. These don't give you D-1, D-2, D-3 though, so that will deviate from Solcast because no past forecasts in sensors.

Others have done similar.

https://community.home-assistant.io/t/solcast-global-solar-power-forecast-integration/334681/419?u=autosteve
https://community.home-assistant.io/t/solcast-global-solar-power-forecast-integration/334681/174?u=autosteve

Search that discussion for ideas!

**Reply by simar7** [reply]
thanks! I am using influxdb to store the data and Grafana to visualize so I need to figure that part out as well as I have the correct data now but I need map the sensors to show the data in the "future". Currently every sensor's data is shown for "today".

**Reply by gcoan** [reply]
It took me ages to work out how to get an Apex chart to show for tomorrow for me, its "offset" you need:

```
type: custom:apexcharts-card
header:
  title: Solar Forecast Tomorrow
  show: true
  show_states: true
  colorize_states: true
apex_config:
  chart:
    height: 300px
  tooltip:
    enabled: true
    shared: true
    followCursor: true
graph_span: 24h
span:
  start: day
  offset: +1day
yaxis:
  - id: kWh
    show: true
    min: 0
    apex_config:
      tickAmount: 10
  - id: header_only
    show: false
series:
  - entity: sensor.solcast_pv_forecast_tomorrow
    name: Forecast
    color: Grey
    opacity: 0.3
    stroke_width: 0
    type: area
    time_delta: +15min
    extend_to: false
    yaxis_id: kWh
    show:
      legend_value: false
      in_header: false
    data_generator: |
      return entity.attributes.detailedForecast.map((entry) => {
            return [new Date(entry.period_start), entry.pv_estimate];
          });
  - entity: sensor.solcast_pv_forecast_tomorrow
    name: Forecast 10%
    color: Grey
    opacity: 0.3
    stroke_width: 0
    type: area
    time_delta: +15min
    extend_to: false
    yaxis_id: kWh
    show:
      legend_value: false
      in_header: false
    data_generator: |
      return entity.attributes.detailedForecast.map((entry) => {
            return [new Date(entry.period_start), entry.pv_estimate10];
          });
  - entity: sensor.solcast_pv_forecast_tomorrow
    yaxis_id: header_only
    name: Tomorrow Forecast
    color: Grey
    offset: '-1day'
    show:
      legend_value: true
      in_header: true
      in_chart: false
      offset_in_name: false
  - entity: sensor.solcast_pv_forecast_tomorrow
    attribute: estimate10
    yaxis_id: header_only
    name: Tomorrow Forecast 10%
    color: Grey
    opacity: 0.3
    offset: '-1day'
    show:
      legend_value: true
      in_header: true
      in_chart: false
      offset_in_name: false
```
