### DISCUSSION TITLE
Automation Suggestion for Free/evaluation accounts limited to 10 API calls per day.

### DISCUSSION THREAD

**Discussion by del13r** [BJReplay/ha-solcast-solar#234] [Ideas]
To find the max frequency I can poll per day, I calculated as follows:
```
24 hours per day / 10 API calls per day = 2.4 hours max poll frequency
* 60 minutes per hour  = 144 minutes max poll frequency
* 60 seconds per minute = 8640 seconds max poll frequency.
```

Due to limitations with using the `trigger: time_pattern` not accepting values over 59 minutes/seconds, I initially just lazily rounded up to the nearest hour which was 3 hours and just set the trigger to happen every 3 hours and that was good enough for me initially.

Example history graph
![image](https://github.com/user-attachments/assets/213aadd8-576f-4055-b9e5-90e275fc8536)

I remember reading that solcast understandably gets hit by waves of requests at the start of the hour due to how the time_pattern feature works and this might be why solcast had previously reduced the number of allowed calls per day.
When I read that, I realized I was also guilty of contributing to that load at the start of the hour by using the 3 hour time_pattern trigger, so I decided to find a way that would maximise my 10 requests per day as well as spread the load away from making API calls at the top of the hour.

Here is what I came up with instead:

```
alias: Solcast PV Forecast update
description: ""
triggers:
  - trigger: template
    value_template: >-
      {{ as_timestamp(utcnow()) -
      as_timestamp(states('sensor.solcast_pv_forecast_api_last_polled')) > 8640
      }}
conditions: []
actions:
  - data: {}
    action: solcast_solar.update_forecasts
mode: single
```

You can check the logic in developer tools / template as well.

Paste this into Template Editor
```
last polled over 8640 seconds ago:
{{ as_timestamp(utcnow()) -
as_timestamp(states('sensor.solcast_pv_forecast_api_last_polled'))
> 8640 }}

seconds since last api poll:
{{ as_timestamp(utcnow()) -
as_timestamp(states('sensor.solcast_pv_forecast_api_last_polled'))
}}

```
Results:
![image](https://github.com/user-attachments/assets/80e52636-8938-44f3-9070-d508f8c24bce)

Obviously everyone has different use cases, but I thought I would share this really basic solution that attempts to help reduce the load on Solcast.
