### DISCUSSION TITLE
Invalid values in Today and Tomorrow Forecasts

### DISCUSSION THREAD

**Discussion by Salada71** [BJReplay/ha-solcast-solar#259] [Q&A]
Hi.
I used this configuration:

```
type: custom:apexcharts-card
header:
  title: Solar forecast
  show: true
  show_states: true
  colorize_states: true
apex_config:
  chart:
    height: 300px
  tooltip:
    enabled: true
    shared: true
    followCursor: true
graph_span: 24h
span:
  start: day
yaxis:
  - id: capacity
    show: true
    opposite: true
    decimals: 0
    max: 100
    min: 0
    apex_config:
      tickAmount: 10
  - id: kWh
    show: true
    min: 0
    apex_config:
      tickAmount: 10
  - id: header_only
    show: false
series:
  - entity: sensor.solaxm_pv_power_total
    transform: return x / 1000
    name: Solar (now)
    type: line
    stroke_width: 2
    float_precision: 2
    color: Orange
    yaxis_id: kWh
    unit: kW
    extend_to: now
    show:
      legend_value: true
      in_header: false
    group_by:
      func: avg
      duration: 5m
  - entity: sensor.solcast_pv_forecast_forecast_today
    name: Forecast
    color: Grey
    opacity: 0.3
    stroke_width: 0
    type: area
    time_delta: +15min
    extend_to: false
    yaxis_id: kWh
    show:
      legend_value: false
      in_header: false
    data_generator: |
      return entity.attributes.detailedForecast.map((entry) => {
            return [new Date(entry.period_start), entry.pv_estimate];
          });
  - entity: sensor.solcast_pv_forecast_forecast_today
    name: Forecast 10%
    color: Grey
    opacity: 0.5
    stroke_width: 0
    type: area
    time_delta: +15min
    extend_to: false
    yaxis_id: kWh
    show:
      legend_value: false
      in_header: false
    data_generator: |
      return entity.attributes.detailedForecast.map((entry) => {
            return [new Date(entry.period_start), entry.pv_estimate10];
          });
  - entity: sensor.solaxm_today_s_solar_energy
    yaxis_id: header_only
    name: Today Actual
    stroke_width: 2
    color: Orange
    show:
      legend_value: true
      in_header: true
      in_chart: false
  - entity: sensor.solcast_pv_forecast_forecast_today
    yaxis_id: header_only
    name: Today Forecast
    color: Grey
    show:
      legend_value: true
      in_header: true
      in_chart: false
  - entity: sensor.solcast_pv_forecast_forecast_tomorrow
    yaxis_id: header_only
    name: Tomorrow Forecast
    color: Grey
    show:
      legend_value: true
      in_header: true
      in_chart: false
  - entity: sensor.solcast_pv_forecast_forecast_remaining_today
    yaxis_id: header_only
    name: Remaining
    color: Grey
    show:
      legend_value: true
      in_header: true
      in_chart: false
```
And I got this: 
![image](https://github.com/user-attachments/assets/d5c8552b-0f6e-4e66-bcdc-8a3a122f17aa)

But if I put the same entities to dashboard, I got this: 
![image](https://github.com/user-attachments/assets/57011b4f-c687-4a4a-8088-f9d8faee62aa)

I do not know, where is problem and what values 3.7 and 3,3 means.

**Comment by autoSteve** [comment]
Back-ticks would be useful to include for code blocks. Makes it so much more readable, especially where indents are concerned. Yours appear totally gone...: ```

Here's what I have for forecast today, and today at 10%. Works fine.

```
    - entity: sensor.solcast_pv_forecast_forecast_today
      yaxis_id: header_only
      name: Forecast today
      color: Grey
      float_precision: 1
      show:
        legend_value: true
        in_header: true
        in_chart: false
    - entity: sensor.solcast_pv_forecast_forecast_today
      attribute: estimate10
      yaxis_id: header_only
      name: Forecast today 10%
      color: Grey
      float_precision: 1
      opacity: 0.3
      show:
        legend_value: true
        in_header: true
        in_chart: false
```

**Reply by autoSteve** [reply]
Enclose the code block thus...

At the start: ```

Your code here...

Then at the end: ```

And hit `Preview` before posting for the win.

**Reply by autoSteve** [reply]
Here is my complete, mostly working custom card-templater code. "Mostly working" because it goes an hour off with the scale in the afternoon. I haven't been bothered giving that any thought for the time being. Bigger fish to fry.

```
type: custom:card-templater
card:
  type: custom:apexcharts-card
  graph_span_template: |-
    {% set sunrise = as_datetime(states('sensor.sun_next_rising'))  %}
    {% set sunset = as_datetime(states('sensor.sun_next_setting'))  %}
    {% if sunrise != none and sunset != none %}
      {% set compressed = (
        (as_local(sunset).hour - as_local(sunrise).hour) + 1 +
        (
          (
            max(now().hour - as_local(sunset).hour, 0)
          )
          if now().hour > as_local(sunrise).hour
          else (as_local(sunrise).hour - now().hour + 2)
        ) * 2
      ) %}
      {% set compressed = compressed + 1 if now().time() > as_local(sunset).time() else compressed %}
      {{ compressed if compressed <= 24 else 24 }}h
    {% else %}
      24h
    {% endif %}
  span:
    start: day
    offset_template: |-
      {% set sunrise = as_datetime(states('sensor.sun_next_rising'))  %}
      {% set sunset = as_datetime(states('sensor.sun_next_setting'))  %}
      {% if sunrise != none and sunset != none %}
        +{{
          (
            as_local(sunrise).hour - max((now().hour - as_local(sunset).hour) + 1, 0)
          )
          if now().hour > as_local(sunrise).hour else now().hour
        }}h
      {% else %}
        +0h
      {% endif %}
  header:
    title: Solar
    show: true
    show_states: true
    colorize_states: true
  apex_config:
    chart:
      height: 300px
    tooltip:
      enabled: true
      shared: true
      followCursor: true
  yaxis:
    - id: capacity
      show: true
      opposite: true
      decimals: 0
      max: 100
      min: 0
      apex_config:
        tickAmount: 10
    - id: kWh
      show: true
      min: 0
      apex_config:
        tickAmount: 10
    - id: header_only
      show: false
  series:
    - entity: sensor.my_home_solar_power
      name: Solar power (5 min avg)
      type: line
      stroke_width: 2
      float_precision: 2
      color: Orange
      yaxis_id: kWh
      unit: kW
      extend_to: now
      show:
        legend_value: true
        in_header: false
      group_by:
        func: avg
        duration: 5m
    - entity: sensor.solcast_pv_forecast_forecast_today
      name: Forecast 10-50%
      color: LightGrey
      opacity: 0.5
      stroke_width: 2
      type: area
      time_delta: +15min
      curve: monotoneCubic
      extend_to: false
      yaxis_id: kWh
      show:
        legend_value: false
        in_legend: true
        in_header: false
      data_generator: |
        return entity.attributes.detailedForecast.map((entry) => {
              return [new Date(entry.period_start), entry.pv_estimate];
            });
    - entity: sensor.powerwall_charge_actual
      name: Battery
      yaxis_id: capacity
      type: line
      stroke_width: 1
      float_precision: 2
      color: DarkGreen
      extend_to: now
      group_by:
        func: avg
        duration: 1s
      show:
        in_legend: true
        legend_value: false
        in_header: false
    - entity: sensor.solcast_pv_forecast_forecast_today
      name: Forecast 10%
      color: White
      opacity: 1
      stroke_width: 0
      type: area
      time_delta: +15min
      curve: monotoneCubic
      extend_to: false
      yaxis_id: kWh
      show:
        in_legend: false
        in_header: false
      data_generator: |
        return entity.attributes.detailedForecast.map((entry) => {
              return [new Date(entry.period_start), entry.pv_estimate10];
            });
    - entity: sensor.solar_generation_today
      yaxis_id: header_only
      name: Actual today
      stroke_width: 2
      color: Orange
      show:
        legend_value: true
        in_header: true
        in_chart: false
    - entity: sensor.solcast_pv_forecast_forecast_today
      yaxis_id: header_only
      name: Forecast today
      color: Grey
      float_precision: 1
      show:
        legend_value: true
        in_header: true
        in_chart: false
    - entity: sensor.solcast_pv_forecast_forecast_today
      attribute: estimate10
      yaxis_id: header_only
      name: Forecast today 10%
      color: Grey
      float_precision: 1
      opacity: 0.3
      show:
        legend_value: true
        in_header: true
        in_chart: false
    - entity: sensor.solcast_pv_forecast_forecast_remaining_today
      yaxis_id: header_only
      name: Forecast remaining
      color: Grey
      show:
        legend_value: true
        in_header: true
        in_chart: false
entities:
  - entity: sensor.five_minute_update
```

**Reply by Salada71** [reply]
Thanks for your code.
I updated my question and formated code. I dont know that it needs to use 3 characters on stsart/end...

But still I do not know, why my values are different on Apex and on Entities.

I used code recommended here but I still cant see correct values. Why I see 3.7 when correct value is 81.51?
Only difference is in entity showing todays real production.
```
- entity: sensor.solcast_pv_forecast_forecast_today
    yaxis_id: header_only
    name: Today Forecast
    color: Grey
    show:
      legend_value: true
      in_header: true
      in_chart: false
```
