### DISCUSSION TITLE
Apex chart no grey area

### DISCUSSION THREAD

**Discussion by davewester** [BJReplay/ha-solcast-solar#310] [Q&A] [answered]
Goodmorning, installed the repo, very happy with the guide to install the repo. I allready had apex running, but now the area of the forcasted are not shown on my charts.
Is this because I have to wait a little bit longer or is there something wrong in my code?

![Screenshot 2025-06-26 at 10-45-55 Standaard woonkamer – Home Assistant](https://github.com/user-attachments/assets/5b4eff5d-b119-4d07-bdff-bafb1a2a56e6)

I have the follwing code: almost a 1on1 copy of the code provided, only changed the sensors of my solarsystem.

``` yaml
type: custom:apexcharts-card
header:
  title: Zonnepanelen
  show: true
  show_states: true
  colorize_states: true
apex_config:
  chart:
    height: 300px
  tooltip:
    enabled: true
    shared: true
    followCursor: true
graph_span: 24h
span:
  start: day
yaxis:
  - id: capacity
    show: true
    opposite: true
    decimals: 0
    max: 100
    min: 0
    apex_config:
      tickAmount: 10
  - id: kWh
    show: true
    min: 0
    apex_config:
      tickAmount: 10
  - id: header_only
    show: false
series:
  - entity: sensor.pv_power
    name: Solar Power (now)
    type: line
    stroke_width: 2
    float_precision: 2
    color: Orange
    yaxis_id: kWh
    unit: kW
    extend_to: now
    show:
      legend_value: true
      in_header: false
    group_by:
      func: avg
      duration: 5m
  - entity: sensor.solcast_pv_forecast_forecast_today
    name: Forecast
    color: Grey
    opacity: 0.3
    stroke_width: 0
    type: area
    time_delta: +15min
    extend_to: false
    yaxis_id: kWh
    show:
      legend_value: false
      in_header: false
    data_generator: |
      return entity.attributes.detailedForecast.map((entry) => {
            return [new Date(entry.period_start), entry.pv_estimate];
          });
  - entity: sensor.solcast_pv_forecast_forecast_today
    name: Forecast 10%
    color: Grey
    opacity: 0.3
    stroke_width: 0
    type: area
    time_delta: +15min
    extend_to: false
    yaxis_id: kWh
    show:
      legend_value: false
      in_header: false
    data_generator: |
      return entity.attributes.detailedForecast.map((entry) => {
            return [new Date(entry.period_start), entry.pv_estimate10];
          });
  - entity: sensor.today_s_pv_generation
    yaxis_id: header_only
    name: Totaal vandaag
    stroke_width: 2
    color: Orange
    show:
      legend_value: true
      in_header: true
      in_chart: false
  - entity: sensor.solcast_pv_forecast_forecast_today
    yaxis_id: header_only
    name: Vandaag voorspeld
    color: Grey
    show:
      legend_value: true
      in_header: true
      in_chart: false
  - entity: sensor.solcast_pv_forecast_forecast_today
    attribute: estimate10
    yaxis_id: header_only
    name: Vandaag voorspeld 10%
    color: Grey
    opacity: 0.3
    show:
      legend_value: true
      in_header: true
      in_chart: false
  - entity: sensor.solcast_pv_forecast_forecast_remaining_today
    yaxis_id: header_only
    name: Resterend
    color: Grey
    show:
      legend_value: true
      in_header: true
      in_chart: false
```
