### DISCUSSION TITLE
v4.0.36 pre-release

### DISCUSSION THREAD

**Discussion by autoSteve** [BJReplay/ha-solcast-solar#72] [General]
I've released v4.0.36 as a pre-release.

v4.0.35 was quiet as a mouse. Thank you to all who tested!

Attributes, attributes, attributes everywhere. Less template sensor madness for all, as home automation is not about doing more, but less, right?

There are attributes calculated for `forecast`, `forecast10`, and `forecast90` for pretty well every sensor. No more YAML loops. These are also broken down by individual Solcast site in some instances.

```
  - sensor:
      - name: "Peak solar today forecast10"
        unique_id: "solcast_pv_forecast_peak_forecast_today_forecast10"
        unit_of_measurement: "W"
        state: >
          {{ state_attr('sensor.solcast_pv_forecast_forecast_remaining_today', 'pv_estimate10') | float(0) }}
  - sensor:
      - name: "West array peak solar forecast today forecast10"
        unique_id: "solcast_pv_forecast_peak_forecast_today_west_array_forecast10"
        unit_of_measurement: "W"
        state: >
          {{ state_attr('sensor.solcast_pv_forecast_peak_forecast_today', 'b68d-c05a-c2b3-2cf9_pv_estimate10') | float(0) }}
  - sensor:
      - name: "Solar forecast production remaining today forecast10"
        unique_id: "solcast_pv_forecast_forecast_remaining_today_forecast10"
        unit_of_measurement: "kW"
        state: >
          {{ state_attr('sensor.solcast_pv_forecast_forecast_remaining_today', 'pv_estimate10') | float(0) }}
```

Happy 4th of July.

## What's Changed
* Additional sensor attributes and logging improvements by @autoSteve

**Full Changelog**: https://github.com/BJReplay/ha-solcast-solar/compare/v4.0.35...v4.0.36
