### DISCUSSION TITLE
Dashboard sharing

### DISCUSSION THREAD

**Discussion by dtswk** [BJReplay/ha-solcast-solar#94] [Show and tell]
Hi all, I thought it would be helpful to have a dedicated thread for sharing UI's.

I've got a simple table I really like showing worst (P10) and estimated forecast.

![image](https://github.com/user-attachments/assets/18c7189c-bbf4-4c1d-b840-e40e1261d10d)

Use this code to create a template
```
  - name: "solcast_7day_summary"
    device_class: enum
    state: standby
    attributes:
      summary: >
        {% set d1 = states.sensor.solcast_pv_forecast_forecast_remaining_today.state | float | round(1) %}
        {% set d2 = states.sensor.solcast_pv_forecast_forecast_tomorrow.state | float | round(1) %}
        {% set d3 = states.sensor.solcast_pv_forecast_forecast_day_3.state | float | round(1) %}
        {% set d4 = states.sensor.solcast_pv_forecast_forecast_day_4.state | float | round(1) %}
        {% set d5 = states.sensor.solcast_pv_forecast_forecast_day_5.state | float | round(1) %}
        {% set d6 = states.sensor.solcast_pv_forecast_forecast_day_6.state | float | round(1) %}
        {% set d7 = states.sensor.solcast_pv_forecast_forecast_day_7.state | float | round(1) %}
        {% set p10_d1 = states.sensor.solcast_pv_forecast_p10_remaining_today.state | float | round(1) %}
        {% set p10_d2 = states.sensor.solcast_pv_forecast_p10_tomorrow.state | float | round(1) %}
        {% set p10_d3 = states.sensor.solcast_pv_forecast_p10_day_3.state | float | round(1) %}
        {% set p10_d4 = states.sensor.solcast_pv_forecast_p10_day_4.state | float | round(1) %}
        {% set p10_d5 = states.sensor.solcast_pv_forecast_p10_day_5.state | float | round(1) %}
        {% set p10_d6 = states.sensor.solcast_pv_forecast_p10_day_6.state | float | round(1) %}
        {% set p10_d7 = states.sensor.solcast_pv_forecast_p10_day_7.state | float | round(1) %}
        {% set ns = namespace(items=[]) %}
        {% set ns.state = 0 %}    
        {% set ns.day = ['Today Remaining', 'Tomorrow', 'Day 3', 'Day 4', 'Day 5', 'Day 6', 'Day 7'] %}     
        {% set ns.pv = [d1,d2,d3,d4,d5,d6,d7] %}
        {% set ns.p10_pv = [p10_d1,p10_d2,p10_d3,p10_d4,p10_d5,p10_d6,p10_d7] %}
        [
        {% for x in range(0, 7) %}
          { 'Day': "{{ ns.day[x] }}", 'pv': {{ ns.pv[x] }}, 'pv10': {{ ns.p10_pv[x] }}}
          {% if not loop.last %},{% endif %}
        {% endfor%}
        ]
```

Then you need to install Flex Table Card from HACS and here is the YAML
```
type: custom:flex-table-card
entities:
  include: sensor.solcast_7day_summary
title: Solar Forecast
columns:
  - name: Day
    data: summary
    modify: x.Day
    align: center
  - data: summary
    name: Worst kWh
    modify: x.pv10
    align: center
  - data: summary
    name: Estimated kWh
    modify: x.pv
    align: center
css:
  table+: 'border-collapse: collapse;'
  th+: 'border: 1px solid white;'
  td+: 'border: 1px solid white;'
```

Matt

**Comment by dtswk** [comment]
Thanks very much to Geoffrey Coan for the original chart..!   

I love this chart, can't help myself and been tweaking.  I am off grid so battery percent is important as once I get beyond solar charging slows down and even stops so to make sense of the solar in I need to see that.  I also found that my solar has a very high reporting rate ie 30 times a second...  So I've slowed down the chart updates as it was constaintly busy.  I also tweaked so that the solar and battery doesn't display past the now line.

My use case is unusual so expect most people may not want so sharing in case there are others.  
 
![image](https://github.com/user-attachments/assets/40dce1f1-309f-462c-9757-f8374cab228c)

```
type: custom:apexcharts-card
update_interval: 1min
header:
  title: Solar forecast
  show: true
  show_states: true
  colorize_states: true
apex_config:
  chart:
    height: 500px
  tooltip:
    enabled: true
    followCursor: true
    shared: true
  xaxis:
    labels:
      datetimeUTC: false
now:
  show: true
  label: Now
graph_span: 14h
span:
  start: day
  offset: +5h
yaxis:
  - id: capacity
    show: true
    opposite: true
    decimals: 0
    max: 100
    min: 0
    apex_config:
      tickAmount: 10
  - id: kWh
    show: true
    min: 0
    apex_config:
      tickAmount: 10
  - id: header_only
    show: false
series:
  - entity: sensor.battery_percent
    yaxis_id: capacity
    type: line
    stroke_width: 2
    float_precision: 2
    color: DarkGreen
    extend_to: now
    group_by:
      func: avg
      duration: 30m
  - entity: sensor.net_solar_production
    transform: return x / 1000;
    name: Solar Power (now)
    type: line
    stroke_width: 2
    float_precision: 2
    color: Orange
    yaxis_id: kWh
    unit: kW
    extend_to: now
    show:
      legend_value: true
      in_header: false
    group_by:
      func: avg
      duration: 30m
  - entity: sensor.solcast_pv_forecast_forecast_today
    name: Forecast
    color: Grey
    opacity: 0.3
    stroke_width: 0
    type: area
    extend_to: false
    group_by:
      func: avg
      duration: 30m
    yaxis_id: kWh
    show:
      legend_value: false
      in_header: false
    data_generator: |
      return entity.attributes.detailedForecast.map((entry) => {
            return [new Date(entry.period_start), entry.pv_estimate];
          });
  - entity: sensor.solcast_pv_forecast_forecast_today
    name: Forecast 10%
    color: Grey
    opacity: 0.3
    stroke_width: 0
    type: area
    extend_to: false
    group_by:
      func: avg
      duration: 30m
    yaxis_id: kWh
    show:
      legend_value: false
      in_header: false
    data_generator: |
      return entity.attributes.detailedForecast.map((entry) => {
            return [new Date(entry.period_start), entry.pv_estimate10];
          });
  - entity: sensor.total_daily_solar
    yaxis_id: header_only
    name: Today Actual
    stroke_width: 2
    color: Orange
    show:
      legend_value: true
      in_header: true
      in_chart: false
  - entity: sensor.solcast_pv_forecast_forecast_today
    yaxis_id: header_only
    name: Today Forecast
    color: Grey
    show:
      legend_value: true
      in_header: true
      in_chart: false
  - entity: sensor.solcast_pv_forecast_forecast_today
    attribute: estimate10
    yaxis_id: header_only
    name: Today Forecast 10%
    color: Grey
    opacity: 0.3
    show:
      legend_value: true
      in_header: true
      in_chart: false
  - entity: sensor.solcast_pv_forecast_forecast_remaining_today
    yaxis_id: header_only
    name: Remaining
    color: Grey
    show:
      legend_value: true
      in_header: true
      in_chart: false
```

**Comment by autoSteve** [comment]
I am getting an interesting time "shift" using @gcoan's example chart. To fix it, and smooth out the lumpy appearance I add two options to the area series.

Today was a brilliantly sunny Winter day, and with the shift of the forecasted values they almost match for much of the day. I did notice that the interpolated "power now"/+30mins/+60mins were off by this same shift, so there might be a code improvement needed there (which I will look into).

```
    time_delta: +15min
    curve: monotoneCubic
```

Before:
<img width="454" alt="image" src="https://github.com/user-attachments/assets/ad9732f6-98e2-40d1-b868-abed50efcfe7">


After:
<img width="458" alt="image" src="https://github.com/user-attachments/assets/8e15f54a-9ad2-4f12-a795-44be11c473b4">

```
type: custom:apexcharts-card
header:
  title: Solar
  show: true
  show_states: true
  colorize_states: true
apex_config:
  chart:
    height: 300px
  tooltip:
    enabled: true
    shared: true
    followCursor: true
graph_span: 15h
span:
  start: day
  offset: +6h
yaxis:
  - id: capacity
    show: true
    opposite: true
    decimals: 0
    max: 100
    min: 0
    apex_config:
      tickAmount: 10
  - id: kWh
    show: true
    min: 0
    apex_config:
      tickAmount: 10
  - id: header_only
    show: false
series:
  - entity: sensor.my_home_solar_power
    name: Solar power (now)
    type: line
    stroke_width: 2
    float_precision: 2
    color: Orange
    yaxis_id: kWh
    unit: kW
    extend_to: now
    show:
      legend_value: true
      in_header: false
    group_by:
      func: avg
      duration: 5m
  - entity: sensor.solcast_pv_forecast_forecast_today
    name: Forecast
    color: Black
    opacity: 1
    stroke_width: 0
    time_delta: +15min
    type: area
    curve: monotoneCubic
    extend_to: false
    yaxis_id: kWh
    show:
      legend_value: false
      in_header: false
    data_generator: |
      return entity.attributes.detailedForecast.map((entry) => {
            return [new Date(entry.period_start), entry.pv_estimate];
          });
  - entity: sensor.solcast_pv_forecast_forecast_today
    name: Forecast 10%
    color: Gray
    opacity: 0.95
    stroke_width: 0
    time_delta: +15min
    type: area
    curve: monotoneCubic
    extend_to: false
    yaxis_id: kWh
    show:
      legend_value: false
      in_header: false
    data_generator: |
      return entity.attributes.detailedForecast.map((entry) => {
            return [new Date(entry.period_start), entry.pv_estimate10];
          });
  - entity: sensor.solar_production_today
    yaxis_id: header_only
    name: Actual today
    stroke_width: 2
    color: Orange
    show:
      legend_value: true
      in_header: true
      in_chart: false
  - entity: sensor.solcast_pv_forecast_forecast_today
    yaxis_id: header_only
    name: Forecast today
    color: Grey
    show:
      legend_value: true
      in_header: true
      in_chart: false
  - entity: sensor.solcast_pv_forecast_forecast_today
    attribute: estimate10
    yaxis_id: header_only
    name: Forecast today 10%
    color: Grey
    opacity: 0.3
    show:
      legend_value: true
      in_header: true
      in_chart: false
  - entity: sensor.solcast_pv_forecast_forecast_remaining_today
    yaxis_id: header_only
    name: Remaining
    color: Grey
    show:
      legend_value: true
      in_header: true
      in_chart: false
```

**Reply by autoSteve** [reply]
Just noticed that "monotoneCubic" does not appear to work, despite the doco. It's using "straight"...

**Reply by autoSteve** [reply]
I am trying out this patch for the spline values to account for the fifteen minute shift...

```
    def get_moment(self, site, _data_field, t):
        return self.fc_moment['all' if site is None else site][self._data_field if _data_field is None else _data_field][(int(t / 300)-3) if int(t / 300) > 2 else 0] # Spline is shifted by 15 minutes
```

(edit) And this...

```
    def get_remaining(self, site, _data_field, t):
        return self.fc_remaining['all' if site is None else site][self._data_field if _data_field is None else _data_field][(int(t / 300)-3) if int(t / 300) > 2 else 0] # Spline is shifted by 15 minutes
```

**Reply by gcoan** [reply]
That's an impressive following of the solcast prediction Steve.

We're in summer at the moment and at best I get about half a day following the prediction, and then half a day of the solar gen going all over the place.  Multiple inverters, multiple roof orientations and so much generation capacity that it pushes the grid voltage above limits all conspire to never give me such a good graph ☹️
Maybe in winter when it's cooler and more predictable.

But back to your graph, I hadn't noticed, but I too see the forecast stepping up at 30min segments. The issue you are seeing must be down to the granularity of the data:
- forecast and forecast 10% are average power for the 30 minute period
- power now is current generation

Could replace the forecast figure with power now predicted sensor which is interpolated, but that'll only give the historic curve not the forward curve.  Or shift by 15 minutes as you've done to improve the "lining up" of the different data series'

**Reply by autoSteve** [reply]
The only reason for the dips in production was feed-in being limited to 5kW after battery filled and afternoon shading. Once the battery had filled I turned on the pool pump and chucked some clothes in the dryer (perverted, I know, because great line drying day 😂), but still couldn't use all the generation.

A fifteen minute shift makes a lot of sense to me, given the 30-minute averages, so I'm glad you concur. I'll monitor over the next few days, as tomorrow is forecast to be a Winter cracker too.

<img width="475" alt="image" src="https://github.com/user-attachments/assets/57502d35-b97a-4be9-9090-cbfc5509b2fb">

**Reply by autoSteve** [reply]
Slight change of plan for the splines code patch. I've instead shifted all the spline arrays by fifteen minutes, achieving the same result, but making more sense in code. I won't bore you with the patch, as it's equivalent to doing what I first thought of.

The Apex chart still needs `time_delta: +15min`, so that is modified in the to-be-proposed readme, dropping `curve: monotoneCubic` because it appears busted in the Lovelace integration code. I'll take a look at that one day...

Testing continues.

**Comment by autoSteve** [comment]
Here's an alternative chart that I've cooked up.

(Edited so many times because issues! This @ 5/09 appears stable and tracks at the moment. 😂🤦🏻)

It has a variable x-axis that changes based on sunrise/sunset throughout the year, and also throughout the day, and is based on 'Lovelace Card Templater' from HACS, `custom:card-templater` which wraps `custom:apexcharts-card` to get the span/offset templates. It updates every five minutes.

<img width="481" alt="image" src="https://github.com/user-attachments/assets/2e5d634b-9e6a-42de-ab73-cbf18ea380fb">

And at 21:09.

<img width="480" alt="image" src="https://github.com/user-attachments/assets/d04bd102-9c35-4dbe-a803-f8b2f7a97ac4">

Full auto-span, 23:38.

<img width="485" alt="image" src="https://github.com/user-attachments/assets/d920aed9-ef94-4909-bdbf-9a82f47a001d">

Just past midnight..

<img width="482" alt="image" src="https://github.com/user-attachments/assets/327b488a-d48f-44b9-9782-de7362cc1caf">

It's not without its idiosyncrasies, flickering when it updates. Not sure why, but I'll work it out.

Template sensor required:

``` yaml
template:
  - trigger:
      - platform: time_pattern
        minutes: "/5"
    sensor:
      - name: "Five Minute Update"
        unique_id: "five_minute_update"
        state: "{{ now().minute }}"
        unit_of_measurement: "Minutes"
```

You probably want to exclude this sensor from the long-term storage in `configuration.yaml`...

``` yaml
recorder:
  purge_keep_days: 14
  exclude:
    entities:
      - sensor.five_minute_update
```

And the actual card.

``` yaml
type: custom:card-templater
card:
  type: custom:apexcharts-card
  graph_span_template: |-
    {% set sunrise = as_datetime(states('sensor.sun_next_rising'))  %}
    {% set sunset = as_datetime(states('sensor.sun_next_setting'))  %}
    {% if sunrise != none and sunset != none %}
      {% set compressed = (
        (as_local(sunset).hour - as_local(sunrise).hour) + 1 +
        (
          (
            max(now().hour - as_local(sunset).hour, 0)
          )
          if now().hour > as_local(sunrise).hour
          else (as_local(sunrise).hour - now().hour + 2)
        ) * 2
      ) %}
      {% set compressed = compressed + 1 if now().time() > as_local(sunset).time() else compressed %}
      {{ compressed if compressed <= 24 else 24 }}h
    {% else %}
      24h
    {% endif %}
  span:
    start: day
    offset_template: |-
      {% set sunrise = as_datetime(states('sensor.sun_next_rising'))  %}
      {% set sunset = as_datetime(states('sensor.sun_next_setting'))  %}
      {% if sunrise != none and sunset != none %}
        +{{
          (
            as_local(sunrise).hour - max((now().hour - as_local(sunset).hour) + 1, 0)
          )
          if now().hour > as_local(sunrise).hour else now().hour
        }}h
      {% else %}
        +0h
      {% endif %}
  header:
    title: Solar
    show: true
    show_states: true
    colorize_states: true
  apex_config:
    chart:
      height: 300px
    tooltip:
      enabled: true
      shared: true
      followCursor: true
  yaxis:
    - id: capacity
      show: true
      opposite: true
      decimals: 0
      max: 100
      min: 0
      apex_config:
        tickAmount: 10
    - id: kWh
      show: true
      min: 0
      apex_config:
        tickAmount: 10
    - id: header_only
      show: false
  series:
    - entity: sensor.my_home_solar_power
      name: Solar power (5 min avg)
      type: line
      stroke_width: 2
      float_precision: 2
      color: Orange
      yaxis_id: kWh
      unit: kW
      extend_to: now
      show:
        legend_value: true
        in_header: false
      group_by:
        func: avg
        duration: 5m
    - entity: sensor.solcast_pv_forecast_forecast_today
      name: Forecast 10-50%
      color: LightGrey
      opacity: 0.5
      stroke_width: 0
      type: area
      time_delta: +15min
      curve: monotoneCubic
      extend_to: false
      yaxis_id: kWh
      show:
        legend_value: false
        in_legend: true
        in_header: false
      data_generator: |
        return entity.attributes.detailedForecast.map((entry) => {
              return [new Date(entry.period_start), entry.pv_estimate];
            });
    - entity: sensor.powerwall_charge_actual
      name: Battery
      yaxis_id: capacity
      type: line
      stroke_width: 1
      float_precision: 2
      color: DarkGreen
      extend_to: now
      group_by:
        func: avg
        duration: 1s
      show:
        in_legend: true
        legend_value: false
        in_header: false
    - entity: sensor.solcast_pv_forecast_forecast_today
      name: Forecast 10%
      color: White
      opacity: 1
      stroke_width: 0
      type: area
      time_delta: +15min
      curve: monotoneCubic
      extend_to: false
      yaxis_id: kWh
      show:
        in_legend: false
        in_header: false
      data_generator: |
        return entity.attributes.detailedForecast.map((entry) => {
              return [new Date(entry.period_start), entry.pv_estimate10];
            });
    - entity: sensor.solar_production_today
      yaxis_id: header_only
      name: Actual today
      stroke_width: 2
      color: Orange
      show:
        legend_value: true
        in_header: true
        in_chart: false
    - entity: sensor.solcast_pv_forecast_forecast_today
      yaxis_id: header_only
      name: Forecast today
      color: Grey
      float_precision: 1
      show:
        legend_value: true
        in_header: true
        in_chart: false
    - entity: sensor.solcast_pv_forecast_forecast_today
      attribute: estimate10
      yaxis_id: header_only
      name: Forecast today 10%
      color: Grey
      float_precision: 1
      opacity: 0.3
      show:
        legend_value: true
        in_header: true
        in_chart: false
    - entity: sensor.solcast_pv_forecast_forecast_remaining_today
      yaxis_id: header_only
      name: Forecast remaining
      color: Grey
      show:
        legend_value: true
        in_header: true
        in_chart: false
entities:
  - entity: sensor.five_minute_update
```

**Reply by gcoan** [reply]
They say a picture paints a thousand words, but in this case you've left us with the YAML and we have to draw the picture in our own minds 🤷‍♂️

**Reply by autoSteve** [reply]
Quite right, Geoff. Shocking generation day, but a picture inserted. It's after sunset now, with the chart already stretching based on time of day.

There is still an issue I find, like now is 18:38 and the chart should run through to 19:00. It doesn't, so the span is off, and I think it is because sunset has now been hit. Might need to add another hour when that happens.

**Reply by autoSteve** [reply]
I think I need to inset this to modify `compressed`. Will monitor, and update if I'm right.

```
      {% set compressed = compressed + 1 if now().time() > as_local(sunset).time() else compressed %}
```

**Reply by gcoan** [reply]
> Template sensor required:

I'm wondering what the need for the 5-minute template sensor is and whether the graph is simpler (and still works) without it?

Currently on a mission to try to reduce the size of my HA database, removing/trimming unnecessary sensors as I keep running out of space on my Google drive to keep sufficient copies of the backup.  The raw db is 2.7Gb (~900Mb compressed) and a lot of it is due to noisy sensors - when I had that period that HA stopping communicating with the world the backups were ~300Mb!
Excellent article https://community.home-assistant.io/t/how-to-keep-your-recorder-database-size-under-control/ 
For example: the 'total solar' power that I only recently created to populate this graph (adding together the individual 3 array power sensors) is my biggest sensor with 176,000 rows on both the state and state_attributes tables.   Whereas a 5-minute time-based trigger template will be around 2500 rows for the same 10 days of 'detailed' history

**Reply by autoSteve** [reply]
It irked me, the whole five minute sensor thing.

I could not find a realiable way to do it just in the card-templater. Every time I tried it flickered madly eventually crashing the front-end, so if you have a suggestion then I am all ears. (This may be a bug with the card-templater...)

The need for the five-minute update? The chart will stop updating if updates are tied to solar actual and battery charge level. Scenario: 'Zero' battery, zero solar generation = no chart update, because values do not change over time. That was how I originally rigged it, and it displeased me.

**Reply by gcoan** [reply]
Ah OK, you want the chart to refresh itself periodically and grow to the right as time advances even if there is no solar generation or battery change, e.g. displaying it on a wall tablet display.

Yes you probably need a sensor that changes to cause the refresh.   For me I don't (yet) have a tablet, only look periodically via the app and website.

You could exclude the 5 minute sensor in the recorder configuration.yaml to stop it filling up the database ...

**Reply by autoSteve** [reply]
(Oops. I have actually done that LTS exclusion, but didn't mention it... Now mentioned.)

**Comment by BJReplay** [comment]
This is a little OT because I can't really share it - none of this is really portable to HA, but I first started using Solcast back in the day when I thought python was a snake.

I still store all my Powerwall data at six second resolution in an SQL Server database, and, up until recently (because I've changed to a tariff where I no longer need to forecast consumption or insolation), was using historical load data, Solcast forecasts, and my own logic to forecast how much to charge, and when.

When I first started forecasting, I discovered that I'd get it wrong, and in trying to work out why, I discovered that forecasting too early was problematic, because (surprise surprise) forecasts change.

Nonetheless, once the code is written and running, it keeps running, and as a result, I have a database going back years with the earliest forecast for each half hour, and the latest.

Here's what it shows for today in Melbourne:

![image](https://github.com/user-attachments/assets/24ed76c7-f330-483d-8e4e-fb8686395bac)

As you can see, expected insolation has fallen off a cliff for today.

And here's what the dashboard shows for yesterday, today, and the next four days.

![image](https://github.com/user-attachments/assets/3d2ee075-4cfd-4bce-9fd7-2eb98636524c)

I eventually refined my algorithm to work out how late it could make its decision based on the remaining time window until peak, the rate that I could charge my battery sufficiently to ride through peak (and, ideally off peak until solar generation was going to exceed load the next day, but failing that, at least peak), and not start charging from the grid until as late as possible, with some margin for changing forecasts, especially if forecast insolation was dropping.

It got to the point that I never paid for peak power, and never over-charged and spilled FIT either, and the algorithm was, in the end, incredibly simple - total load to breakeven point (insolation exceeds load) less remaining insolation = shortfall.  That's how much I needed to charge.

Charge rate was known, and with a few tweaks, the algorithm would push up the battery reserve level to try to make the shortfall = 0 by the beginning of peak.

AI and machine learning be damned.

Now my charge cost is $0.00 for two hours a day, which is enough to add 10kWh every day - should I need to.

No need for forecasts until that tariff is no longer available.  However, with the way the market is in Victoria, that's unlikely to go away any time soon.

**Comment by IzSmithh** [comment]
Hi all, 
Great share. 
Gotta thanks everyone for the great work with Solcast. THANKS Again...
I'm a 2–3 month-old, non coder newbie here.

So, was wondering if anyone could help me out with tomorrows forecast?
Its more useful to me then the weather report. I get a great sense what to except.
Situation is, 
if i offset the start day by +1 i see the graph and BUT no header information
if i don't offset I see headers info and NO graph
![Screenshot_7-12-2024_204211_192 168 1 201](https://github.com/user-attachments/assets/265f6e45-f90d-4f5f-9447-086ce4cc6a65)
Would also be really cool if I/We could use the tap action to open tomorrows graph up (I tried but couldn't)
if it is, are previous days doable? 

Just today I added my house load to the OG graph to test out. (I know it was a terrible solar day today here in Sydney)
Unfortunatly can't show any of the previes days as i dont know how to store them.
![Screenshot_7-12-2024_21936_192 168 1 201](https://github.com/user-attachments/assets/620e52bc-15a4-46b4-9049-ddc004202690)

**Reply by autoSteve** [reply]
Glad to hear you're enjoying the integration, @IzSmithh.

Previous day forecasts are only retrievable by calling the action solcast_solar.query_forecast_data. I guess one could populate the attributes of a template sensor with that to visualise it. Not sure why one would want to do so, but, as the Energy dashboard will show the past quite well, just not with thirty-minute resolution. It's in the past. Let it go... 😂

Your attempted Apex for tomoz would help. The headings would need to reference things like this:

```
    - entity: sensor.solcast_pv_forecast_forecast_tomorrow
      yaxis_id: header_only
      name: Forecast tomorrow
      ...
```

```
    - entity: sensor.solcast_pv_forecast_forecast_tomorrow
      attribute: estimate10
      yaxis_id: header_only
      name: Forecast tomorrow 10%
      ...
```

**Reply by gcoan** [reply]
Here's my YAML for a 'tomorrow and day after and day after' forecast

I turned the legends off at the bottom of the chart as they just cluttered the screen up.  Oh yes and my sensors have the double forecast_forecast bit in the name removed as I didn't like it, so renamed the sensors.  If you have the default config you'll have to revert the sensors names

```
type: custom:apexcharts-card
apex_config:
  chart:
    height: 300px
  legend:
    show: false
all_series_config:
  unit: " kWh"
header:
  title: Future Solar forecast
  show: true
  show_states: true
  colorize_states: true
graph_span: 3d
span:
  start: day
  offset: +1day
now:
  show: true
  label: Now
yaxis:
  - id: kwh
    min: 0
    apex_config:
      tickAmount: 5
  - id: header_only
    show: false
series:
  - entity: sensor.solcast_pv_forecast_tomorrow
    yaxis_id: kwh
    type: area
    name: Tomorrow
    color: grey
    opacity: 0.3
    data_generator: |
      var today = entity.attributes.detailedForecast.map((start, index) => {
        return [new Date(start["period_start"]).getTime(), entity.attributes.detailedForecast[index]["pv_estimate"]];
      });
      var data = today
      return data;
    show:
      legend_value: false
      in_header: false
    stroke_width: 1
    float_precision: 2
    extend_to: false
  - entity: sensor.solcast_pv_forecast_tomorrow
    yaxis_id: kwh
    type: area
    name: Tomorrow 10%
    color: grey
    opacity: 0.3
    data_generator: |
      var today = entity.attributes.detailedForecast.map((start, index) => {
        return [new Date(start["period_start"]).getTime(), entity.attributes.detailedForecast[index]["pv_estimate10"]];
      });
      var data = today
      return data;
    show:
      legend_value: false
      in_header: false
    stroke_width: 0
    float_precision: 2
    extend_to: false
  - entity: sensor.solcast_pv_forecast_tomorrow
    yaxis_id: kwh
    type: area
    name: Tomorrow 90%
    color: grey
    opacity: 0.3
    data_generator: |
      var today = entity.attributes.detailedForecast.map((start, index) => {
        return [new Date(start["period_start"]).getTime(), entity.attributes.detailedForecast[index]["pv_estimate90"]];
      });
      var data = today
      return data;
    show:
      legend_value: false
      in_header: false
    stroke_width: 0
    float_precision: 2
    extend_to: false
  - entity: sensor.solcast_pv_forecast_day_3
    yaxis_id: kwh
    type: area
    name: Day 3
    color: grey
    opacity: 0.3
    data_generator: |
      var today = entity.attributes.detailedForecast.map((start, index) => {
        return [new Date(start["period_start"]).getTime(), entity.attributes.detailedForecast[index]["pv_estimate"]];
      });
      var data = today
      return data;
    show:
      legend_value: false
      in_header: false
    stroke_width: 1
    float_precision: 2
    extend_to: false
  - entity: sensor.solcast_pv_forecast_day_3
    yaxis_id: kwh
    type: area
    name: Day 3 10%
    color: grey
    opacity: 0.3
    data_generator: |
      var today = entity.attributes.detailedForecast.map((start, index) => {
        return [new Date(start["period_start"]).getTime(), entity.attributes.detailedForecast[index]["pv_estimate10"]];
      });
      var data = today
      return data;
    show:
      legend_value: false
      in_header: false
    stroke_width: 0
    float_precision: 2
    extend_to: false
  - entity: sensor.solcast_pv_forecast_day_3
    yaxis_id: kwh
    type: area
    name: Day 3 90%
    color: grey
    opacity: 0.3
    data_generator: |
      var today = entity.attributes.detailedForecast.map((start, index) => {
        return [new Date(start["period_start"]).getTime(), entity.attributes.detailedForecast[index]["pv_estimate90"]];
      });
      var data = today
      return data;
    show:
      legend_value: false
      in_header: false
    stroke_width: 0
    float_precision: 2
    extend_to: false
  - entity: sensor.solcast_pv_forecast_day_4
    yaxis_id: kwh
    type: area
    name: Day 4
    color: grey
    opacity: 0.3
    data_generator: |
      var today = entity.attributes.detailedForecast.map((start, index) => {
        return [new Date(start["period_start"]).getTime(), entity.attributes.detailedForecast[index]["pv_estimate"]];
      });
      var data = today
      return data;
    show:
      legend_value: false
      in_header: false
    stroke_width: 1
    float_precision: 2
    extend_to: false
  - entity: sensor.solcast_pv_forecast_day_4
    yaxis_id: kwh
    type: area
    name: Day 4 10%
    color: grey
    opacity: 0.3
    data_generator: |
      var today = entity.attributes.detailedForecast.map((start, index) => {
        return [new Date(start["period_start"]).getTime(), entity.attributes.detailedForecast[index]["pv_estimate10"]];
      });
      var data = today
      return data;
    show:
      legend_value: false
      in_header: false
    stroke_width: 0
    float_precision: 2
    extend_to: false
  - entity: sensor.solcast_pv_forecast_day_4
    yaxis_id: kwh
    type: area
    name: Day 4 90%
    color: grey
    opacity: 0.3
    data_generator: |
      var today = entity.attributes.detailedForecast.map((start, index) => {
        return [new Date(start["period_start"]).getTime(), entity.attributes.detailedForecast[index]["pv_estimate90"]];
      });
      var data = today
      return data;
    show:
      legend_value: false
      in_header: false
    stroke_width: 0
    float_precision: 2
    extend_to: false
  - entity: sensor.solcast_pv_forecast_tomorrow
    yaxis_id: header_only
    name: Tomorrow Forecast
    color: grey
    offset: "-1day"
    show:
      legend_value: true
      in_header: true
      in_chart: false
      offset_in_name: false
  - entity: sensor.solcast_pv_10_forecast_tomorrow
    yaxis_id: header_only
    name: Tomorrow 10% Forecast
    color: grey
    offset: "-1day"
    show:
      legend_value: true
      in_header: true
      in_chart: false
      offset_in_name: false
  - entity: sensor.solcast_pv_forecast_day_3
    yaxis_id: header_only
    name: Day 3 Forecast
    color: blue
    offset: "-1day"
    show:
      legend_value: true
      in_header: true
      in_chart: false
      offset_in_name: false
  - entity: sensor.solcast_pv_forecast_day_4
    yaxis_id: header_only
    name: Day 4 Forecast
    color: blue
    offset: "-1day"
    show:
      legend_value: true
      in_header: true
      in_chart: false
      offset_in_name: false
```

**Reply by IzSmithh** [reply]
@autoSteve, yes you're absolutely right. i will let it go :)
and thanks for all the hard work you and your team have put inn.

@gcoan, thank you for the code. i ended up following your lead and got rid of the double forecasts. 
just had to but the "attribute: estimate 10" in "entity: sensor.solcast_pv_forecast_tomorrow"

Now my graphs page looks like this. and don't mind the others as im testing and not sure if figures are right
![Screenshot_8-12-2024_124530_192 168 1 201](https://github.com/user-attachments/assets/aefb793f-b77d-4c60-96f4-0fe721a2b0fb)

**Reply by gcoan** [reply]
> just had to but the "attribute: estimate 10" in "entity: sensor.solcast_pv_forecast_tomorrow"

Ah yes, sorry, I have today and tomorrow 10% forecast helper sensors, just to make it easier to display on dashboards and graph the history (which Steve will hate me doing).  I'd forgotten that I was using that in the chart

Your graphs look fine, nice idea to show load power alongside solar forecast.  Very much the Australian summer, I'm forecasting 2.1kWh total generation today and much the same for the next few days.  Gloomy winter weather here in the UK

**Reply by autoSteve** [reply]
I was super jealous of you guys in the Northern five months ago, Geoff. Now feeling super smug and wearing shorts with the pool at 29°C.

Switching to three free power hours between 11AM and 2PM (thanks @BJReplay) mean that I have been paid for power use since the start of November, not billed. Could have been October too, but I took a while to get my head around the whole VPP thing, where I need to do the scheduling. The dramatic battery drop is me dumping ~13kWh of stored energy that I won't need to the grid in short order at 'super' peak payback rate. (It is annoying that doing so seems to curtail the micro-inverters. Ah, well. What evs. Enphase and Tesla kind-of play nicely together. Mostly.)

<img width="504" alt="image" src="https://github.com/user-attachments/assets/0e7e697a-f5e7-45e8-ab48-3ba0376897f0">

**Reply by BJReplay** [reply]
I have finally got around to less dramatic dumping (half the storage), thanks, @autoSteve, though I can probably go harder, only third day of trying.

Yesterday was a combination of a sunny day, putting 11kWh into the EV from solar (and a little bit of battery / grid in the morning), stopping when excess solar !> charging load, then dumping when excess solar !> household load until battery SoC <= 70%.

Right now, Solar > household load and minimum SoC was 33, so I probably could have dumped until 50%.

![Screenshot_20241209_072704_Home Assistant.jpg](https://github.com/user-attachments/assets/5cbda257-cc6b-465b-a89d-eb80d9c3bcea)

![Screenshot_20241209_072144_Home Assistant.jpg](https://github.com/user-attachments/assets/4daf4c92-e7eb-464c-a938-2d6ee871b1f1)

**Reply by gcoan** [reply]
Further enhancement to my chart above, the x-axis labels by default are formatted as DD MMM, e.g. 14 Dec

I can't remember the date but the day of the week is more useful to me, so I changed the x-axis format:

```
apex_config:
  chart:
    height: 300px
  legend:
    show: false
  xaxis:
    labels:
      format: ddd, dd
```

Can use any format string, e.g. ddd dd MMM will display Mon 14 Dec but the labels are centred on the start of the day, so adding more text results in them shifting further to the left.  Despite looking at the manual I couldn't find a way to centre-align the labels under the data, so shortened the label instead
