### ISSUE TITLE
Hyphens in attribute names break Jinja2

### ISSUE THREAD

**Issue by autoSteve** [BJReplay/ha-solcast-solar#262]
### Discussed in https://github.com/BJReplay/ha-solcast-solar/discussions/260

<div type='discussions-op-text'>

<sup>Originally posted by **gcoan** March 31, 2025</sup>
I have for a long time had the Apex chart (posted in the readme) working for showing total PV forecast vs total PV generation.

Was interested in seeing a similar forecast vs actual for my largest array, in particular to better understand when clipping might occur.  Can use the peak forecast time and peak forecast power which have this data per-site (array orientation) but a graph would be easier to use.

I turned on the configuration option to ‘enable site breakdown for half-hourly/hourly detail attributes’ and I can see new attributes detailedForecast-siteid with estimate/estimate10/estimate90, but when I changed the Apex chart to use this new attribute it doesn’t work.

Stripping back the Apex chart to the minimum I have the following in my dashboard

``` yaml
      - type: custom:apexcharts-card
        header:
          title: Solar Forecast Today
          show: true
          show_states: true
          colorize_states: true
        apex_config:
          chart:
            height: 300px
          tooltip:
            enabled: true
            shared: true
            followCursor: true
        all_series_config:
          unit: ' kWh'
        graph_span: 24h
        span:
          start: day
        now:
          show: true
        yaxis:
          - id: kWh
            show: true
            min: 0
            apex_config:
              tickAmount: 10
          - id: header_only
            show: false
        series:
          - entity: sensor.g_sd2237g182_pv_power
            name: G PV Power
            type: line
            stroke_width: 1
            float_precision: 2
            color: Red
            yaxis_id: kWh
            unit: kW
            extend_to: now
            show:
              legend_value: false
              in_header: false
            group_by:
              func: avg
              duration: 5min
          - entity: sensor.solcast_pv_forecast_today
            name: G Forecast
            color: Purple
            stroke_width: 1
            type: line
            extend_to: false
            yaxis_id: kWh
            unit: kW
            show:
              legend_value: false
              in_header: false
            data_generator: |
              return entity.attributes.detailedForecast-XXX.map((entry) => {
                    return [new Date(entry.period_start), entry.pv_estimate];
                  });
```

XXX is my site id

The Apex chart takes ages to render and when it does, the purple line for site forecast doesn’t appear.

If I change the data_generator, replacing ‘detailedForecast-XXX’ with ‘detailedForecast’ to just pull the overall forecast, it works fine (and quickly).
Thinking it might be a problem with the length of the attribute name, I copied the site specific forecast and created it as a new attribute called ‘detailedForecast-x’,  same result, takes ages to render and then doesn’t display the purple line.

Tried with both sites, same result.

I can’t see anything different in the sensor attributes, only thing mentioned is that these site specific detailed attributes are not written to the HA database, might that be the problem?</div>
